{% set version = "2.0.0" %}

package:
  name: tzlocal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tzlocal/tzlocal-{{ version }}.tar.gz
  sha256: 949b9dd5ba4be17190a80c0268167d7e6c92c62b30026cf9764caf3e308e5590

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip

  run:
    - python
    - pytz

test:
  imports:
    - tzlocal

about:
  home: https://github.com/regebro/tzlocal
  license: MIT
  license_file: LICENSE.txt
  summary: 'tzinfo object for the local timezone'
  dev_url: https://github.com/regebro/tzlocal

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - synapticarbors
