travis:
  secure:
    BINSTAR_TOKEN: ffbBnzH+yDgF+k336gMtZR0Qf+RIVU5ttJUqdihgKB1SeDym5aAJCnuNFEAaXr2vtXMoU98oBgCkVuTSWQiP1Zx/4+oF56QUj2UZkSoMK/DR79wnwNnAZVnlGKHHyd89gmjo4UM75nbektax4ALc1lOpshEdzo62zGmXWRZniwTYEwNrCnbedNd97vA0fsxDupJdrMfTxD5t2cZsUYq8QLmBOQ45OXfKuXnZkW9M66I6liu2nzfd4BagBF4tiS8bi9mwYchQLP6TY+JDrQ+/b41KCQK5wCCUzUp/guv3OWUeb9RTgLoVTAAXI1lWCNHd6sFDpbZZqOtdKwUmP+KltuzEsvNuR4Q9utNztWKnckcJn21Tj5FvpBNUzYxwg+1cWPJJVQwi91vt6aTiR1918BwMpbVkyp+XWI/t6l+qzkrFK9P23wUJufVKnNH4dSk0t2KRwfClR0+WaV8pnRgNp6wear2rW7mYoaOPh3YTsWdSnADf6jmnhUStlvZGSj6I2UPV1Jv2ZMfv1qIO/JAqMk8alqr3TjcLgI0AfLxAWf2XRXD2ylvIjzSnXl1Qpq3nUfOjYd587rClEfBKh9TckZmRrE1G7EdYOuM9fu4w83PuGvv6vrVrZWtJfuJd8oTLMyybs1qyBKJmBXhsM2tH/iruklsVwSeP1JlkwaA6vaU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
